[platformio]
default_envs = esp32-s3-touch-amoled-216

[env:esp32-s3-touch-amoled-216]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -I .
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_LVGL_H_INCLUDE_SIMPLE

lib_deps =
  bblanchon/ArduinoJson@7.4.2
  lvgl/lvgl@8.4.0
  moononournation/GFX Library for Arduino@1.6.4
  lewisxhe/SensorLib@0.3.3
  lewisxhe/XPowersLib@0.2.6
